### ISSUE TITLE
Canvas indexes in warning/error output

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/tripoli#10]
This would help pinpoint particular canvases that have a problem -- related to #9

**Comment by lexpar** [comment]
I've put together a [new class to represent paths ](https://github.com/DDMAL/tripoli/blob/dev/tripoli/validator_logging.py#L25) which has allowed me to add indexes to the paths, while still allowing 'unique logging' behaviour (that is, if *every* canvas has the same error, only one instance of that logged error will be saved.

This will get into 1.1, which is planned for the end of the week.

**Comment by ahankinson** [comment]
👍 💯

**Comment by lexpar** [comment]
This just got merge in. You should see the changes applied on validate.musiclibs.net.
