### ISSUE TITLE
Update documentation on PyPI

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/tripoli#11]
The documentation needs to be updated here.

https://pypi.python.org/pypi/tripoli

**Comment by lexpar** [comment]
It done.

**Comment by ahankinson** [comment]
This has gone missing again. You should ensure it's automatically included in the release process, instead of manually added on PyPI (there is a way to do this).

**Comment by lexpar** [comment]
The way to do it is the `long_description` kwarg in setup. I copied from `requests` and copy in the README and HISTORY on deployment. Should be fixed for good now. :)

8436eef5a863163def72dd674ad86ed8aa56e36b
