### ISSUE TITLE
Incorrect warning on annotation @id

### ISSUE THREAD

**Issue by irv** [DDMAL/tripoli#13]
I think this warning is a misunderstanding:
`Warning: annotation SHOULD have @id field. @ data['sequences']['canvases']['images']['@id']`

from the 2.1 specification http://iiif.io/api/presentation/2.1/#image-resources

> Annotations *may* have their own URIs, conveyed by adding an @id property to the JSON object, and if so *should* be HTTP URIs

**Comment by lexpar** [comment]
Thanks for the correction! Just pushed through an update.
