### ISSUE TITLE
HTML validation

### ISSUE THREAD

**Issue by azaroth42** [DDMAL/tripoli#14]
There are a lot of requirements around HTML that do not seem to be tested? Might be nice to declare manifests with nasty script injections as invalid :)

See: http://iiif.io/api/presentation/2.1/#html-markup-in-property-values

**Comment by lexpar** [comment]
Thanks for pointing this out! Will work it in to the next update.

**Comment by lexpar** [comment]
I've added [HTML checking logic](https://github.com/DDMAL/tripoli/blob/dev/tripoli/resource_validators/base_validator.py#L488) that should be applied to every string field which is not having its value equality-checked against a set of valid values.

This will end up in the 1.1 release, which I'll probably put out at the end of the week.

**Comment by lexpar** [comment]
This has been merged into master. If you find any issues with the HTML validation logic, please open a new issue.
