### ISSUE TITLE
Add small demo webserver

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/tripoli#4]
This is low priority.

It might be useful to have a demonstration server where a URL to a manifest can be provided and a validation report returned. 

HTML + API interface would be nice.

Should be possible to do with the built-in Python `http.server`

https://docs.python.org/3.5/library/http.server.html?highlight=http.server#module-http.server

**Comment by lexpar** [comment]
Built a small site using flask with a single page that can validate via URLs posted in. Does json and text/html. 

https://github.com/DDMAL/tripoli/tree/master/web
