### ISSUE TITLE
Unhashable Type location in manifest

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/tripoli#8]
Probably just as much a musiclibs error, but this manifest:

http://digi.vatlib.it/iiif/MSS_Arch.Cap.S.Pietro.B.79/manifest.json

gives an error "unhashable type: 'list'" when trying to import it to musiclibs.

It would be helpful (if possible) if Tripoli was able to give the location in the manifest for this.

**Comment by lexpar** [comment]
Indeed it's a musiclibs problem (something I'm doing after validation), as the manifest validates with errors and warnings on the validator.

https://validate.musiclibs.net/?manifest=http%3A%2F%2Fdigi.vatlib.it%2Fiiif%2FMSS_Arch.Cap.S.Pietro.B.79%2Fmanifest.json

**Comment by lexpar** [comment]
https://github.com/DDMAL/musiclibs/issues/112
